### ISSUE TITLE
Not able to login in to the router 

### ISSUE THREAD

**Issue by nagesh-c** [jbemmel/srl-rift#1]
Hi,

I'm trying to run this on Mac, was able to successfully run and deploy the router.

If I try to login it is asking for password:
bash-5.1# ssh linuxadmin@clab-openrift-lab-node1
linuxadmin@clab-openrift-lab-node1's password:

What is the password for this ? Or do I need to exchange keys.

**Comment by jbemmel** [comment]
Thank you for your comment.

The easiest way is to copy your ssh key into the authorized_keys file, and then rebuild the container. I'll add a note
